# **Cleaning the datasets**
---

chapters for navigation:

## Environment Setup and Library Imports

In [62]:
import pandas as pd
import glob 
import os
import pyarrow

## Crime Data

### 1. Project Context: 

> 🔗 **Data Dictionary:** [Police UK API Documentation](https://data.police.uk/about/)

* **Row Granularity:** Each row represents an individual crime at a specific stage of the investigation process. 
* **The Update Mechanism:** The `crime_id` serves as the primary identifier. The appearance of duplicate `crime_id` values across the dataset is not an error; it indicates that the case status (`last_outcome_category`) has been retroactively updated.
* **The ASB Anomaly (Systemic Nulls):** There is a perfect 1:1 correlation where missing `crime_id` values exclusively map to Anti-social behaviour (ASB) incidents with missing `last_outcome_category`. This is a structural feature of how the police log these specific events.
* **ASB Deduplication Strategy:** Because ASB incidents lack unique identifiers, multiple incidents occurring in the same location during the same month manifest as exact row duplicates. To preserve true crime volume, these are treated as distinct events and retained. 
* **Known Upstream Limitations:** Although official Police UK documentation notes that certain forces occasionally duplicate specific ASB incident logs upstream, there is no way to isolate these systemic logging errors from genuinely repeated local incidents. Hence, this pipeline proceeds under the assumption that all ASB rows represent unique events.

### 2. Data Profiling and Diagnostics

To establish the dataset's schema and identify necessary transformations prior to data merging, a single-month sample (`2024-01-metropolitan-street.csv`) was profiled. 

**Key Diagnostic Findings & Transformation Strategy:**

* **Primary Key Anomalies (`crime_id`):** Diagnostic checks confirmed that `crime_id` violates standard primary key constraints. It contains high volumes of missing values (ASB incidents) and duplicate strings (errors or case updates). *Action: Deduplication followed by dropping of `crime_id`.*
* **Zero-Variance & Redundant Features:** The `context` and `falls_within` columns exhibit zero statistical variance. *Action: Drop these features.*
* **Memory & Data Type Optimisation:** 
    * **Temporal Data:** The `Month` column is currently formatted as a string object. *Action: Cast to a `datetime` object.*
    * **Categorical Data:** Text-heavy columns with repeating values (e.g., `crime_type`, `last_outcome_category`) are currently stored as memory-heavy strings. *Action: Must be converted to `category` data types to drastically compress the final memory usage.*

In [2]:
# Load the test sample  
df = pd.read_csv('data/raw/crime/2024-01/2024-01-metropolitan-street.csv')

# Initial exploration of the data - shape, datatypes, missing values
df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,e5b3ed0375b796067eb668f37a18094cce300bdbd5446c...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.552328,50.853155,On or near Queen Street,E01031392,Arun 001C,Other theft,Unable to prosecute suspect,NaN
1,d5d46efe4a74b2fdf87f28f7c89c4d7534c80d4150f58f...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.666558,50.848940,On or near Northfields Lane,E01031396,Arun 003D,Violence and sexual offences,Status update unavailable,NaN
2,8ee491f5ebeda54bda879fed602d2f308bfd8abf4b59f7...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.657460,50.787270,On or near Kingsmead,E01031419,Arun 015C,Violence and sexual offences,Status update unavailable,NaN
3,318e91d9bd9ad081bb348b8c743236365c9178eb60229d...,2024-01,Metropolitan Police Service,Metropolitan Police Service,0.876815,51.147655,On or near Parking Area,E01034986,Ashford 005G,Violence and sexual offences,Status update unavailable,NaN
4,8ec949bf76f02215ad73b489ff502ab32101b0834b49fc...,2024-01,Metropolitan Police Service,Metropolitan Police Service,0.884060,51.110654,On or near Southdown Close,E01034989,Ashford 010G,Violence and sexual offences,Status update unavailable,NaN

In [4]:
df.shape

(91411, 12)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 91411 entries, 0 to 91410
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Crime ID               74897 non-null  str
 1   Month                  91411 non-null  str
 2   Reported by            91411 non-null  str
 3   Falls within           91411 non-null  str
 4   Longitude              90739 non-null  float64
 5   Latitude               90739 non-null  float64
 6   Location               91411 non-null  str
 7   LSOA code              90739 non-null  str
 8   LSOA name              90739 non-null  str
 9   Crime type             91411 non-null  str
 10  Last outcome category  74897 non-null  str
 11  Context                0 non-null      float64
dtypes: float64(3), str(9)
memory usage: 26.8 MB

In [6]:
df.describe()

          Longitude      Latitude  Context
count  90739.000000  90739.000000      0.0
mean      -0.121020     51.511942      NaN
std        0.157308      0.081372      NaN
min       -4.219770     50.701061      NaN
25%       -0.196748     51.473003      NaN
50%       -0.118025     51.514829      NaN
75%       -0.033954     51.552337      NaN
max        1.411904     54.966167      NaN

In [9]:
#Checking the type of missingness for the 'Crime ID' column
df.loc[df['Crime ID'].isnull()].value_counts(dropna=False)
df.loc[df['Crime ID'].isnull(), ['Crime type', 'Last outcome category']].value_counts(dropna=False)
df.loc[df['Crime type'] == 'Anti-social behaviour', 'Crime ID'].value_counts(dropna=False)

Crime ID
NaN    16514
Name: count, dtype: int64

In [10]:
# Check for uniqueness to identify zero-variance and redundant columns
df.nunique()

Crime ID                 71871
Month                        1
Reported by                  1
Falls within                 1
Longitude                30508
Latitude                 29575
Location                 22080
LSOA code                 5251
LSOA name                 5251
Crime type                  14
Last outcome category       13
Context                      0
dtype: int64

### 3. Merging the Crime Datasets

In [3]:
files_path = 'data/raw/crime'
files = glob.glob(os.path.join(files_path, "**", "*.csv"), recursive=True)
keep_cols = ['Crime ID', 'Month', 'Reported by', 'Longitude', 'Latitude', 'LSOA code', 'LSOA name', 'Crime type', 'Last outcome category'] # List of columns to keep from the raw data files.
# Use ignore_index=True to prevent custom indices being used and hence index collision. 
df_merged = pd.concat([pd.read_csv(f, usecols=keep_cols) for f in files], ignore_index=True)

In [ ]:
# Check merge has been successful
df_merged.info()
df_merged.sample(10)

<class 'pandas.DataFrame'>
RangeIndex: 3665530 entries, 0 to 3665529
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               str
 1   Month                  str
 2   Reported by            str
 3   Longitude              float64
 4   Latitude               float64
 5   LSOA code              str
 6   LSOA name              str
 7   Crime type             str
 8   Last outcome category  str
dtypes: float64(2), str(7)
memory usage: 797.2 MB

,Crime ID,Month,Reported by,Longitude,Latitude,LSOA code,LSOA name,Crime type,Last outcome category
1262907,12f9e3cd1a1b3196b365c2753e8f61b1d2986bcfe1c78a...,2024-08,Metropolitan Police Service,0.197163,51.543668,E01002264,Havering 026E,Possession of weapons,Investigation complete; no suspect identified
997895,33100c8531ebff586a752130c4074660cf91601817a5de...,2024-06,Sussex Police,-0.896230,50.927165,E01031507,Chichester 007B,Vehicle crime,Investigation complete; no suspect identified
1572532,7cf6aaeb1aa44fe17d764e7c7b81ccc8a4ddb8c19537ce...,2024-10,Metropolitan Police Service,0.165476,51.609527,E01002307,Havering 003E,Vehicle crime,Status update unavailable
3187229,9b685f27a75e1539372c6ac706a44658bccdd8efea11a4...,2025-08,West Midlands Police,-1.790989,52.521006,E01009096,Birmingham 029A,Violence and sexual offences,Awaiting court outcome
2643321,cc321a94a725e637ff2421060061daf3891c588b02b5d7...,2025-05,Metropolitan Police Service,-0.081298,51.504238,E01033884,Southwark 035A,Burglary,Investigation complete; no suspect identified
1516193,df6e9b463c80ed2bfa9688b13f7226f7ecaf52a7a95b91...,2024-09,West Midlands Police,-1.435138,52.397093,E01009543,Coventry 033D,Shoplifting,Investigation complete; no suspect identified
1115388,bbce50f46d930eb74423177585f5eb8606d447458a30bb...,2024-07,Metropolitan Police Service,-0.105860,51.460573,E01003044,Lambeth 018B,Violence and sexual offences,Unable to prosecute suspect
1415393,0645aa3f3ba7338c06d4cb54cb081da44b33466a9f8a57...,2024-09,Metropolitan Police Service,-0.133618,51.588109,E01002020,Haringey 021A,Robbery,Investigation complete; no suspect identified
761499,e5661cdb646cd0cbedddfe4671aae99162d02832c0f61a...,2024-05,Metropolitan Police Service,-0.098216,51.659076,E01001471,Enfield 010C,Vehicle crime,Investigation complete; no suspect identified
1111411,NaN,2024-07,Metropolitan Police Service,-0.190349,51.491070,E01002898,Kensington and Chelsea 017E,Anti-social behaviour,NaN

### 4. Data Standardisation and Deduplication

In [4]:
# Standardise the column names 
df_merged.columns = df_merged.columns.str.lower().str.replace(' ', '_')

In [5]:
# Convert column data types
df_merged['month'] = pd.to_datetime(df_merged['month'])
# Sort the data by month so can remove non-updated crimes
df_merged = df_merged.sort_values('month', ascending=True)
# Convert categorical columns to category dtype to save memory and improve performance
df_merged[['reported_by', 'lsoa_code', 'lsoa_name', 'crime_type', 'last_outcome_category']] = df_merged[['reported_by', 'lsoa_code', 'lsoa_name', 'crime_type', 'last_outcome_category']].astype('category')

In [6]:
# Find non-ASB exact duplicate rows, and drop these - these are genuine errors.
duplicate_mask = df_merged.duplicated(keep='first') #flags the redundant copies 
df_duplicates = df_merged[duplicate_mask]
df_duplicates['crime_type'].value_counts() #2483 rows lead to 5524 exactly duplicated non-ASB rows, so need to drop 3041 rows

crime_type
Anti-social behaviour           247123
Violence and sexual offences      1553
Public order                       757
Drugs                              319
Robbery                            148
Criminal damage and arson           75
Burglary                            71
Vehicle crime                       34
Theft from the person               29
Other theft                         24
Other crime                         11
Possession of weapons               10
Shoplifting                          9
Bicycle theft                        1
Name: count, dtype: int64

In [6]:
# Split into ASB and non-ASB to remove all duplicates from the non-ASB data
with_id = df_merged[df_merged['crime_id'].notnull()]
no_id = df_merged[df_merged['crime_id'].isnull()]

In [18]:
# Checking the values add up correctly after splitting the data
print(with_id['crime_id'].nunique()) #There are 13050 rows which need to be dropped - 3041 exact duplicates and 10009 non-updated crimes.
print(len(no_id)) 
print(len(with_id))

3042350
610130
3052359

In [7]:
# Remove exact duplicate rows from non-ASB data
with_id = with_id.drop_duplicates(keep='last') 
print(len(with_id)) #3041 have been dropped

3052359

In [8]:
# Remove non-updated versions of crimes
with_id_clean = with_id.drop_duplicates(subset='crime_id', keep='last') #10009 further rows dropped - the non-updated crimes. Could also just run this to remove the exact duplicates too. 
print(len(with_id_clean))

3042350

In [22]:
no_id.duplicated().sum()

np.int64(247123)

In [ ]:
#Merge back together
df_merged = pd.concat([with_id_clean, no_id], ignore_index=True)
# Check the de-duplicated data
df_merged.info() #3652480 rows, 8 columns, correct datatypes
df_merged.sample(10)
df_merged.duplicated().sum() #only duplicates remaining stem from ASB data.

<class 'pandas.DataFrame'>
RangeIndex: 3652480 entries, 0 to 3652479
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   crime_id               str
 1   month                  datetime64[us]
 2   reported_by            category
 3   longitude              float64
 4   latitude               float64
 5   lsoa_code              category
 6   lsoa_name              category
 7   crime_type             category
 8   last_outcome_category  category
dtypes: category(5), datetime64[us](1), float64(2), str(1)
memory usage: 323.5 MB

np.int64(247123)

In [26]:
#drop crime_id column as not needed anymore - can just use index. 
df_merged.drop(columns='crime_id', inplace=True)

### 5. Handling Missing Values
Now, the missingness of values in other columns are explored.

In [28]:
#Check for missing values
df_merged.isnull().sum()

month                         0
reported_by                   0
longitude                 21861
latitude                  21861
lsoa_code                 21865
lsoa_name                 21865
crime_type                    0
last_outcome_category    610130
dtype: int64

In [ ]:
# Show that every row missing longitude is also missing latitude, LSOA name, and LSOA code
df_geospatial_missing = df_merged[df_merged['longitude'].isnull()]
print(len(df_geospatial_missing)) 
df_geospatial_missing[['latitude', 'lsoa_name', 'lsoa_code']].isnull().sum()

21861

latitude     21861
lsoa_name    21861
lsoa_code    21861
dtype: int64

In [33]:
# There are also 4 rogue rows with geospatial data but no LSOA data
df_lsoa_missing = df_merged[df_merged[['lsoa_code', 'lsoa_name']].isnull().any(axis=1)]
print(len(df_lsoa_missing))

21865

Roughly 0.6 % of the data is missing geospatial coordinates. All these rows are also missing LSOA data. The respective values in the `month`, `reported_by`, `crime_type`, and `last_outcome_category` columns are explored to ascertain whether these are related to the missing values.

In [ ]:
# Look at total distribution of months in overall population and missing data
display(df_merged['month'].value_counts(normalize=True) * 100 , df_geospatial_missing['month'].value_counts(normalize=True) * 100)

month
2025-07-01    4.638793
2024-07-01    4.517068
2025-06-01    4.402187
2024-10-01    4.401667
2024-05-01    4.386280
2025-05-01    4.365390
2024-08-01    4.335493
2024-06-01    4.331742
2025-08-01    4.314411
2025-10-01    4.238846
2024-11-01    4.201146
2025-03-01    4.167059
2024-09-01    4.147100
2025-04-01    4.121912
2024-03-01    4.093931
2024-04-01    4.061514
2025-09-01    4.056066
2025-11-01    4.051193
2023-12-01    3.965935
2024-01-01    3.936887
2024-12-01    3.926264
2024-02-01    3.849029
2025-01-01    3.817926
2025-02-01    3.672162
Name: proportion, dtype: float64

month
2024-01-01    6.248571
2023-12-01    6.179955
2024-10-01    4.867115
2024-07-01    4.670418
2024-08-01    4.592654
2024-11-01    4.519464
2024-05-01    4.464572
2024-09-01    4.432551
2025-10-01    4.400531
2024-06-01    4.295320
2025-09-01    4.185536
2025-11-01    4.084900
2024-12-01    4.007136
2025-03-01    3.979690
2025-07-01    3.933946
2025-08-01    3.860757
2025-02-01    3.828736
2024-04-01    3.485659
2025-04-01    3.389598
2025-05-01    3.389598
2024-03-01    3.339280
2025-01-01    3.320983
2025-06-01    3.266090
2024-02-01    3.256942
Name: proportion, dtype: float64

In [47]:
# Look at total distribution of police forces in overall population and missing data
display(df_merged['reported_by'].value_counts(normalize=True) * 100 , df_geospatial_missing['reported_by'].value_counts(normalize=True) * 100)

reported_by
Metropolitan Police Service    62.129129
West Midlands Police           18.291900
Thames Valley Police           10.776459
Sussex Police                   8.802512
Name: proportion, dtype: float64

reported_by
Sussex Police                  55.486940
Thames Valley Police           38.360551
Metropolitan Police Service     6.152509
West Midlands Police            0.000000
Name: proportion, dtype: float64

In [48]:
# Look at total distribution of crime type in overall population and missing data
display(df_merged['crime_type'].value_counts(normalize=True) * 100 , df_geospatial_missing['crime_type'].value_counts(normalize=True) * 100)

crime_type
Violence and sexual offences    28.470491
Anti-social behaviour           16.704540
Shoplifting                      8.405467
Other theft                      8.397527
Vehicle crime                    7.639412
Criminal damage and arson        5.869710
Public order                     5.561509
Theft from the person            5.389297
Burglary                         4.304774
Drugs                            3.484153
Robbery                          2.336577
Other crime                      1.434231
Bicycle theft                    1.160746
Possession of weapons            0.841565
Name: proportion, dtype: float64

crime_type
Violence and sexual offences    42.866292
Public order                     7.794703
Other theft                      7.790129
Shoplifting                      7.451626
Drugs                            6.760898
Criminal damage and arson        6.070171
Other crime                      4.853392
Vehicle crime                    4.286172
Anti-social behaviour            3.316408
Theft from the person            2.804080
Burglary                         2.127076
Possession of weapons            1.944101
Robbery                          1.070399
Bicycle theft                    0.864553
Name: proportion, dtype: float64

In [49]:
# Look at total distribution of last outcome categories in overall population and missing data
display(df_merged['last_outcome_category'].value_counts(normalize=True) * 100 , df_geospatial_missing['last_outcome_category'].value_counts(normalize=True) * 100)

last_outcome_category
Investigation complete; no suspect identified          48.859369
Unable to prosecute suspect                            33.246043
Status update unavailable                               5.279767
Court result unavailable                                3.556790
Local resolution                                        2.526238
Awaiting court outcome                                  2.311503
Under investigation                                     1.988036
Action to be taken by another organisation              1.073512
Offender given a caution                                0.523181
Further investigation is not in the public interest     0.240932
Offender given penalty notice                           0.164281
Formal action is not in the public interest             0.134304
Further action is not in the public interest            0.066297
Suspect charged as part of another case                 0.029517
Offender given a drugs possession warning               0.000230
Name: proportion, dtype: float64

last_outcome_category
Investigation complete; no suspect identified          34.618660
Unable to prosecute suspect                            27.479182
Status update unavailable                              19.530659
Local resolution                                        4.745458
Court result unavailable                                4.168244
Under investigation                                     3.524792
Awaiting court outcome                                  1.821537
Action to be taken by another organisation              1.703255
Offender given a caution                                0.908403
Further investigation is not in the public interest     0.804315
Formal action is not in the public interest             0.250757
Further action is not in the public interest            0.227101
Suspect charged as part of another case                 0.137207
Offender given penalty notice                           0.080431
Offender given a drugs possession warning               0.000000
Name: proportion, dtype: float64

**Missing Data Conclusions**

* `month`:  December 2023 and January 2024 are significantly over-represented in the missing data (12% combined). This isolated spike suggests a temporary upstream IT failure. 
* `reported_by`: Sussex Police and Thames Valley Police are responsible for 94% of missing geospatial data in this dataset, indicating differing infrastructure or internal processes at the forces level. 
* `crime_type`: Violence and sexual offences are significantly over-represented in the missing data (43% of unmapped data vs. 28% of overall volume). This geospatial censoring is deliberate to protect victim anonymity. Meanwhile, Anti-social behaviour is under-represented (3% of unmapped vs. 17% overall).
* `last_outcome_category`: 'Status update unavailable' is significantly over-represented in the missing data (20%), suggesting that geospatial data is restricted for complex crimes.

**Action Taken**
I have decided to drop the rows with missing geospatial data from the merged dataset. They account for only **0.6%** of total crimes, making their overall statistical impact negligible. While forces such as Sussex Police made up a disproportionate amount of missing records, it is important to contextualise this loss: only 5% of their total reported volume is being discarded. Ultimately, as exact coordinates are key for joining crime metrics to local property markets, retaining missing geospatial data offers zero analytical value to the final analysis.

In [ ]:
# Drop missing geospatial data from the merged dataset 
df_merged = df_merged.dropna(subset=['lsoa_code']) 
# Verify missing rows have been removed 
print(len(df_merged))

3630615

month                         0
reported_by                   0
longitude                     0
latitude                      0
lsoa_code                     0
lsoa_name                     0
crime_type                    0
last_outcome_category    609405
dtype: int64

### 6. Final Validation and Export
Finally, save the file as a Parquet file, ready for EDA analysis.

In [60]:
# Check for anymore missing values
df_merged.isna().sum()
# Add new category to last_outcome_category to avoid TypeError
df_merged['last_outcome_category'] = df_merged['last_outcome_category'].cat.add_categories('No outcome recorded (ASB Protocol)')
# Replace null values with new category for ASB crimes
df_merged.loc[df_merged['crime_type'] == 'Anti-social behaviour', 'last_outcome_category'] = df_merged.loc[df_merged['crime_type'] == 'Anti-social behaviour', 'last_outcome_category'].fillna('No outcome recorded (ASB Protocol)')
# Final check for missing values
df_merged.isna().sum()

month                    0
reported_by              0
longitude                0
latitude                 0
lsoa_code                0
lsoa_name                0
crime_type               0
last_outcome_category    0
dtype: int64

In [63]:
df_merged.to_parquet('data/processed/cleaned_crime_data.parquet', engine='pyarrow', index=False)