# **Cleaning the datasets**
---

chapters for navigation:

## Crime Data

### 1. Environment Setup and Library Import

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob 
import os
import pyarrow

Context: - should this be part of the data dictionary?
Data dictionary link: https://data.police.uk/about/

Each row represents an individual crime (linked to 1 or more individuals) at each stage of the update process. Duplicate `Crime ID` values represent when an outcome is updated.
There is a perfect 1:1 correlation for rows with missing `Crime ID`, `Crime type` of anti-social behaviour (ASB), and missing `Last outcome category`.
Because instances of ASB have missing `Crime ID' values, and they don't get updated, there are many exact duplicate rows. These occur when an ASB incident occurs more than once in the same location within the same month, and cannot be assumed to be errors.

### 2. Data Profiling and Diagnostics

2024-01-metropolitan-street.csv was used as a test sample here.


Issues identified:

Primary Key `Crime ID` has missing and duplicate values.

Remove zero-variance/redundant columns: context, falls within

Action:

Remove duplicated `Crime ID` rows, keeping the most recent ID, then drop this column. 


To be acted on entire concatenated dataset below:

**Profiling Decisions:**
* **Retain:** `LSOA code`, `Longitude`, and `Latitude`. These are critical primary keys required to join Office for National Statistics (ONS) population data and HM Land Registry house prices in later phases.
* **Drop:** `Context` (100% null), `Reported by` (zero-variance), and `Falls within` (zero-variance). Removing these will significantly reduce memory overhead during the full ingestion phase.

In [11]:
# Load the test sample  
df = pd.read_csv('data/raw/crime/2024-01/2024-01-metropolitan-street.csv')

# Initial exploration of the data
df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,e5b3ed0375b796067eb668f37a18094cce300bdbd5446c...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.552328,50.853155,On or near Queen Street,E01031392,Arun 001C,Other theft,Unable to prosecute suspect,NaN
1,d5d46efe4a74b2fdf87f28f7c89c4d7534c80d4150f58f...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.666558,50.848940,On or near Northfields Lane,E01031396,Arun 003D,Violence and sexual offences,Status update unavailable,NaN
2,8ee491f5ebeda54bda879fed602d2f308bfd8abf4b59f7...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.657460,50.787270,On or near Kingsmead,E01031419,Arun 015C,Violence and sexual offences,Status update unavailable,NaN
3,318e91d9bd9ad081bb348b8c743236365c9178eb60229d...,2024-01,Metropolitan Police Service,Metropolitan Police Service,0.876815,51.147655,On or near Parking Area,E01034986,Ashford 005G,Violence and sexual offences,Status update unavailable,NaN
4,8ec949bf76f02215ad73b489ff502ab32101b0834b49fc...,2024-01,Metropolitan Police Service,Metropolitan Police Service,0.884060,51.110654,On or near Southdown Close,E01034989,Ashford 010G,Violence and sexual offences,Status update unavailable,NaN

In [12]:
df.shape

(91411, 12)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 91411 entries, 0 to 91410
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Crime ID               74897 non-null  str
 1   Month                  91411 non-null  str
 2   Reported by            91411 non-null  str
 3   Falls within           91411 non-null  str
 4   Longitude              90739 non-null  float64
 5   Latitude               90739 non-null  float64
 6   Location               91411 non-null  str
 7   LSOA code              90739 non-null  str
 8   LSOA name              90739 non-null  str
 9   Crime type             91411 non-null  str
 10  Last outcome category  74897 non-null  str
 11  Context                0 non-null      float64
dtypes: float64(3), str(9)
memory usage: 26.8 MB

In [14]:
df.describe()

          Longitude      Latitude  Context
count  90739.000000  90739.000000      0.0
mean      -0.121020     51.511942      NaN
std        0.157308      0.081372      NaN
min       -4.219770     50.701061      NaN
25%       -0.196748     51.473003      NaN
50%       -0.118025     51.514829      NaN
75%       -0.033954     51.552337      NaN
max        1.411904     54.966167      NaN

In [30]:
#Checking the type of missingness for the 'Crime ID' column
df.loc[df['Crime ID'].isnull()].value_counts(dropna=False)
df.loc[df['Crime ID'].isnull(), ['Crime type', 'Last outcome category']].value_counts(dropna=False)

Crime type             Last outcome category
Anti-social behaviour  NaN                      16514
Name: count, dtype: int64

In [32]:
df.loc[df['Crime type'] == 'Anti-social behaviour', 'Crime ID'].value_counts(dropna=False)

Crime ID
NaN    16514
Name: count, dtype: int64

In [ ]:
# Check for uniqueness to identify zero-variance and redundant columns
df.nunique()

Crime ID                 71871
Month                        1
Reported by                  1
Falls within                 1
Longitude                30508
Latitude                 29575
Location                 22080
LSOA code                 5251
LSOA name                 5251
Crime type                  14
Last outcome category       13
Context                      0
dtype: int64

Merge the data

In [93]:
files_path = 'data/raw/crime'
files = glob.glob(os.path.join(files_path, "**", "*.csv"), recursive=True)
keep_cols = ['Crime ID', 'Month', 'Reported by', 'Longitude', 'Latitude', 'LSOA code', 'LSOA name', 'Crime type', 'Last outcome category'] 
# Use ignore_index=True to prevent custom indices being used and hence index collision. 
df_merged = pd.concat([pd.read_csv(f, usecols=keep_cols) for f in files], ignore_index=True)

In [94]:
#check merge has been successful
df_merged.info()
df_merged.sample(10)

<class 'pandas.DataFrame'>
RangeIndex: 3665530 entries, 0 to 3665529
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               str
 1   Month                  str
 2   Reported by            str
 3   Longitude              float64
 4   Latitude               float64
 5   LSOA code              str
 6   LSOA name              str
 7   Crime type             str
 8   Last outcome category  str
dtypes: float64(2), str(7)
memory usage: 797.2 MB

,Crime ID,Month,Reported by,Longitude,Latitude,LSOA code,LSOA name,Crime type,Last outcome category
3561597,8e0ae9b6a6bf4ee8ae49a1fd4d4259f426305134d6f25e...,2025-11,Metropolitan Police Service,-0.420186,51.504562,E01034616,Hillingdon 030F,Robbery,Under investigation
2017957,0bde491095e8d21a1c16ad63b6c91d139c403b11992e81...,2025-01,Metropolitan Police Service,-0.080478,51.527173,E01033708,Hackney 033C,Violence and sexual offences,Investigation complete; no suspect identified
3503247,f693d72cd7cb938fb36bddcb03e87c80c3286794ba518d...,2025-10,West Midlands Police,-1.562110,52.409660,E01009695,Coventry 023A,Other crime,Investigation complete; no suspect identified
238569,b54e354857159106a25b2e94b791314b713fb63aa4d6d7...,2024-01,Metropolitan Police Service,-0.144433,51.496234,E01004750,Westminster 023E,Violence and sexual offences,Investigation complete; no suspect identified
725841,ac118324be31254585fb3551f9d658c9e05876c4bc04b7...,2024-04,West Midlands Police,-2.117560,52.442298,E01009832,Dudley 042A,Violence and sexual offences,Investigation complete; no suspect identified
3417206,965e027c5156113517eb327fd1e4df1f41d60c4b0721c3...,2025-10,Metropolitan Police Service,-0.158802,51.500372,E01002818,Kensington and Chelsea 012A,Vehicle crime,Investigation complete; no suspect identified
2101988,6bd016c8376beebf5e61db4ed057f5e039386a1a19723b...,2025-01,West Midlands Police,-1.919832,52.534522,E01009237,Birmingham 024A,Shoplifting,Unable to prosecute suspect
982311,d109de55dacf73c40f57b753745a1a9796a1f6f69a7fb8...,2024-06,Metropolitan Police Service,-0.150348,51.470393,E01004565,Wandsworth 005A,Theft from the person,Investigation complete; no suspect identified
3330293,e1e280747746604bb624edf978f2c7fc74173a99717750...,2025-09,Thames Valley Police,-0.610123,51.504988,E01016463,Slough 009B,Vehicle crime,Investigation complete; no suspect identified
1571570,NaN,2024-10,Metropolitan Police Service,-0.339159,51.580776,E01002129,Harrow 023C,Anti-social behaviour,NaN

Put into action the changes

In [95]:
# Standardise the column names 
df_merged.columns = df_merged.columns.str.lower().str.replace(' ', '_')

In [96]:
# Convert column data types
df_merged['month'] = pd.to_datetime(df_merged['month'])
# Sort the data by month so can remove non-updated crimes
df_merged = df_merged.sort_values('month', ascending=True)

df_merged[['reported_by', 'lsoa_code', 'lsoa_name', 'crime_type', 'last_outcome_category']] = df_merged[['reported_by', 'lsoa_code', 'lsoa_name', 'crime_type', 'last_outcome_category']].astype('category')

**The next step is to ensure each crime ID is unique so each row represents one unique crime with its final update. Duplicated Crime IDs are removed.**

In [97]:
# Find non-ASB exact duplicate rows, and drop these - these are the errors.
duplicate_mask = df_merged.duplicated(keep='first') #flags the redundant copies 
df_duplicates = df_merged[duplicate_mask]
df_duplicates['crime_type'].value_counts() #2483 rows lead to 5524 exactly duplicated rows within non-ASB - need to drop 3041 rows

crime_type
Anti-social behaviour           247123
Violence and sexual offences      1553
Public order                       757
Drugs                              319
Robbery                            148
Criminal damage and arson           75
Burglary                            71
Vehicle crime                       34
Theft from the person               29
Other theft                         24
Other crime                         11
Possession of weapons               10
Shoplifting                          9
Bicycle theft                        1
Name: count, dtype: int64

In [98]:
# Split into ASB and non-ASB to remove all duplicates from the non-ASB data, and then merge back together.
with_id = df_merged[df_merged['crime_id'].notnull()]
no_id = df_merged[df_merged['crime_id'].isnull()]

In [99]:
print(with_id['crime_id'].nunique()) #3042350 - means that there are 13050 rows which need to be dropped - 3041 exact duplicates and 10009 non-updated crimes.
print(len(no_id)) #610130, ASB
print(len(with_id)) #3055400, non-ASB

3042350
610130
3055400

In [100]:
# Remove exact duplicate rows
with_id = with_id.drop_duplicates(keep='last') 
print(len(with_id)) #3041 have been dropped

3052359

In [ ]:
# Remove non-updated versions of crimes
with_id_clean = with_id.drop_duplicates(subset='crime_id', keep='last') #10009 further rows dropped - the non-updated crimes. Could also just run this to remove exact duplicates too. 
print(len(with_id_clean))

3042350

In [105]:
#Merge back together and drop crime_id column as not needed anymore.
df_merged = pd.concat([with_id_clean, no_id], ignore_index=True)
df_merged.drop(columns='crime_id', inplace=True)

In [107]:
# Check the de-duplicated data
df_merged.info() #3652480 rows 
df_merged.sample(10)

<class 'pandas.DataFrame'>
RangeIndex: 3652480 entries, 0 to 3652479
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   month                  datetime64[us]
 1   reported_by            category
 2   longitude              float64
 3   latitude               float64
 4   lsoa_code              category
 5   lsoa_name              category
 6   crime_type             category
 7   last_outcome_category  category
dtypes: category(5), datetime64[us](1), float64(2)
memory usage: 109.0 MB

,month,reported_by,longitude,latitude,lsoa_code,lsoa_name,crime_type,last_outcome_category
111223,2023-12-01,Metropolitan Police Service,-0.433393,51.537489,E01002429,Hillingdon 019C,Burglary,Investigation complete; no suspect identified
413603,2024-03-01,West Midlands Police,-1.777552,52.353425,E01010189,Solihull 029E,Other theft,Investigation complete; no suspect identified
2572641,2025-08-01,West Midlands Police,-1.513041,52.450849,E01032587,Coventry 043E,Violence and sexual offences,Unable to prosecute suspect
1104520,2024-08-01,Metropolitan Police Service,-0.105699,51.408827,E01001160,Croydon 002D,Violence and sexual offences,Unable to prosecute suspect
1792581,2025-02-01,Metropolitan Police Service,-0.126529,51.354045,E01004088,Sutton 019C,Violence and sexual offences,Unable to prosecute suspect
806771,2024-06-01,Thames Valley Police,-0.970308,51.424278,E01016437,Reading 018B,Vehicle crime,Unable to prosecute suspect
1939501,2025-03-01,Thames Valley Police,-1.445758,51.402564,E01016302,West Berkshire 018C,Violence and sexual offences,Local resolution
2193807,2025-05-01,Thames Valley Police,-0.803398,52.007758,E01034465,Milton Keynes 036F,Shoplifting,Investigation complete; no suspect identified
1589237,2024-12-01,West Midlands Police,-1.891331,52.482070,E01033617,Birmingham 050F,Shoplifting,Court result unavailable
832139,2024-06-01,Metropolitan Police Service,-0.295788,51.572277,E01000575,Brent 007D,Violence and sexual offences,Unable to prosecute suspect

go up to handle missigness, remmeber to fillna for last outcome ctageory, add proper markdown and work out how to categorise the cleaning process

**Now, the missingness of values in other columns than the primary key are explored.**

In [104]:
#Check for missing values
df_merged.isnull().sum()

crime_id                 610130
month                         0
reported_by                   0
longitude                 21861
latitude                  21861
lsoa_code                 21865
lsoa_name                 21865
crime_type                    0
last_outcome_category    610130
dtype: int64

In [21]:
df_merged.isnull().sum() #21861 longitude and latitude values are missing, and 21865 LSOA names. Everything else intact. 

#could fill in missing values here for crime IDs with 'ASB' and last outcome category for ASB 

df_merged.loc[df_merged['Longitude'].isnull(), ['Latitude', 'LSOA name']].value_counts(dropna=False) #this shows that every row missing longitude is also missing latitude and LSOA name
df_merged.loc[df_merged['LSOA name'].isnull(), ['Crime ID', 'Latitude', 'Longitude', 'Month', 'Reported by']].value_counts() #4 rows that are missing LSOA but not geospatial variables

Crime ID                                                          Latitude   Longitude  Month       Reported by
313acb161af3eae87ab6569441726be06c9d1906e24c962d4fbf4552f7e054d8  54.585701  -6.005104  2024-11-01  Sussex Police                  1
4ac3a5e54fc38403a6dd0d9624a8b31c57ea7e1d812ff8e9f850cba5296ce37c  54.589707  -6.789849  2024-11-01  Metropolitan Police Service    1
a3f00b306b63807392f6e46b0b3cdff15e323f0573dea332c4d368ac4683d04d  54.428177  -6.581064  2024-05-01  Sussex Police                  1
b0877d237222c11fab4ca0669e51e41c9f035889bb1ef6bd45c6fa59e1c2e1f8  54.833107  -6.339279  2024-11-01  Sussex Police                  1
Name: count, dtype: int64

In [67]:
df_merged['Month'].value_counts(normalize=True) #total ocurrences of months throughout the dataset

Month
2025-07-01    0.046388
2024-07-01    0.045171
2025-06-01    0.044022
2024-10-01    0.044017
2024-05-01    0.043863
2025-05-01    0.043654
2024-08-01    0.043355
2024-06-01    0.043317
2025-08-01    0.043144
2025-10-01    0.042388
2024-11-01    0.042011
2025-03-01    0.041671
2024-09-01    0.041471
2025-04-01    0.041219
2024-03-01    0.040939
2024-04-01    0.040615
2025-09-01    0.040561
2025-11-01    0.040512
2023-12-01    0.039659
2024-01-01    0.039369
2024-12-01    0.039263
2024-02-01    0.038490
2025-01-01    0.038179
2025-02-01    0.036722
Name: proportion, dtype: float64

In [65]:
df_merged.loc[df_merged['Longitude'].isnull(), 'Month'].value_counts(normalize=True) #ocurrences of missing geospatial data for each month - if MCAR, these should reflect the overall proportions given above.
#Conclusion: Month is not a factor

Month
2024-01-01    0.062486
2023-12-01    0.061800
2024-10-01    0.048671
2024-07-01    0.046704
2024-08-01    0.045927
2024-11-01    0.045195
2024-05-01    0.044646
2024-09-01    0.044326
2025-10-01    0.044005
2024-06-01    0.042953
2025-09-01    0.041855
2025-11-01    0.040849
2024-12-01    0.040071
2025-03-01    0.039797
2025-07-01    0.039339
2025-08-01    0.038608
2025-02-01    0.038287
2024-04-01    0.034857
2025-04-01    0.033896
2025-05-01    0.033896
2024-03-01    0.033393
2025-01-01    0.033210
2025-06-01    0.032661
2024-02-01    0.032569
Name: proportion, dtype: float64

In [23]:
df_merged['Reported by'].value_counts(normalize=True)

Reported by
Metropolitan Police Service    0.621291
West Midlands Police           0.182919
Thames Valley Police           0.107765
Sussex Police                  0.088025
Name: proportion, dtype: float64

In [25]:
df_merged.loc[df_merged['Longitude'].isnull(), 'Reported by'].value_counts(normalize=True) 
#Conclusion: MAR, sussex and Thames Valley are way more likely to have missing geospatial data.
#West Midlands have no missing geospatial data at all
#If removing all these rows, more likely to be removing sussex and thames rows...will underestimate crimes happening there!
#If keeping in, just remember to factor it into analysis

Reported by
Sussex Police                  0.554869
Thames Valley Police           0.383606
Metropolitan Police Service    0.061525
Name: proportion, dtype: float64

In [27]:
df_merged['Crime type'].value_counts(normalize=True)

Crime type
Violence and sexual offences    0.284705
Anti-social behaviour           0.167045
Shoplifting                     0.084055
Other theft                     0.083975
Vehicle crime                   0.076394
Criminal damage and arson       0.058697
Public order                    0.055615
Theft from the person           0.053893
Burglary                        0.043048
Drugs                           0.034842
Robbery                         0.023366
Other crime                     0.014342
Bicycle theft                   0.011607
Possession of weapons           0.008416
Name: proportion, dtype: float64

In [29]:
df_merged.loc[df_merged['Longitude'].isnull(), 'Crime type'].value_counts(normalize=True)
#Conclusions: MAR again...geospatial data more liekly to be missing if it's a violence and sexual offence. 
#geospatial data actually less likely to be missing if ASB: they just record the data, then move on.

Crime type
Violence and sexual offences    0.428663
Public order                    0.077947
Other theft                     0.077901
Shoplifting                     0.074516
Drugs                           0.067609
Criminal damage and arson       0.060702
Other crime                     0.048534
Vehicle crime                   0.042862
Anti-social behaviour           0.033164
Theft from the person           0.028041
Burglary                        0.021271
Possession of weapons           0.019441
Robbery                         0.010704
Bicycle theft                   0.008646
Name: proportion, dtype: float64

In [35]:
df_merged['Last outcome category'].value_counts(normalize=True, dropna=False)

Last outcome category
Investigation complete; no suspect identified          0.406976
Unable to prosecute suspect                            0.276924
NaN                                                    0.167045
Status update unavailable                              0.043978
Court result unavailable                               0.029626
Local resolution                                       0.021042
Awaiting court outcome                                 0.019254
Under investigation                                    0.016559
Action to be taken by another organisation             0.008942
Offender given a caution                               0.004358
Further investigation is not in the public interest    0.002007
Offender given penalty notice                          0.001368
Formal action is not in the public interest            0.001119
Further action is not in the public interest           0.000552
Suspect charged as part of another case                0.000246
Offender given a drugs possession warning              0.000002
Name: proportion, dtype: float64

In [37]:
df_merged.loc[df_merged['Longitude'].isnull(), 'Last outcome category'].value_counts(normalize=True, dropna=False)
#Conclusions: MAR again...geospatial data more liekly to be missing if the status update is not available. Shows that when status isnt available, geospatial data is hidden.

Last outcome category
Investigation complete; no suspect identified          0.334706
Unable to prosecute suspect                            0.265679
Status update unavailable                              0.188829
Local resolution                                       0.045881
Court result unavailable                               0.040300
Under investigation                                    0.034079
NaN                                                    0.033164
Awaiting court outcome                                 0.017611
Action to be taken by another organisation             0.016468
Offender given a caution                               0.008783
Further investigation is not in the public interest    0.007776
Formal action is not in the public interest            0.002424
Further action is not in the public interest           0.002196
Suspect charged as part of another case                0.001327
Offender given penalty notice                          0.000778
Name: proportion, dtype: float64

**Finally, save the file as a Parquet file, ready for EDA analysis.**

In [39]:
df_merged.to_parquet('data/cleaned_crime_data.parquet', engine='pyarrow', index=False)